-- Adds French passé simple conjugation bank rows for review before applying.
-- 38 verbs x 6 pronouns = 228 rows. This does not alter app code or live data until run.

insert into public.conjugation_questions (
  language,
  verb,
  verb_group,
  tense,
  pronoun,
  correct_answer,
  options,
  grade_levels,
  difficulty_level
)
select
  v.language,
  v.verb,
  v.verb_group,
  v.tense,
  v.pronoun,
  v.correct_answer,
  v.options,
  v.grade_levels,
  v.difficulty_level
from (
values
  ('fr-FR', 'aimer', 'groupe_1', 'passé simple', 'je', 'aimai', '["aimai","aimas","aima","aimâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'aimer', 'groupe_1', 'passé simple', 'tu', 'aimas', '["aima","aimâmes","aimâtes","aimas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'aimer', 'groupe_1', 'passé simple', 'il/elle', 'aima', '["aimâtes","aimèrent","aima","aimâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'aimer', 'groupe_1', 'passé simple', 'nous', 'aimâmes', '["aimai","aimâmes","aimâtes","aimèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'aimer', 'groupe_1', 'passé simple', 'vous', 'aimâtes', '["aimâtes","aimèrent","aimai","aimas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'aimer', 'groupe_1', 'passé simple', 'ils/elles', 'aimèrent', '["aimai","aimas","aima","aimèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'chanter', 'groupe_1', 'passé simple', 'je', 'chantai', '["chantâmes","chantâtes","chantai","chanta"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'chanter', 'groupe_1', 'passé simple', 'tu', 'chantas', '["chantèrent","chantas","chantâmes","chantâtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'chanter', 'groupe_1', 'passé simple', 'il/elle', 'chanta', '["chanta","chantâtes","chantèrent","chantai"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'chanter', 'groupe_1', 'passé simple', 'nous', 'chantâmes', '["chantèrent","chantai","chantas","chantâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'chanter', 'groupe_1', 'passé simple', 'vous', 'chantâtes', '["chantas","chanta","chantâtes","chantai"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'chanter', 'groupe_1', 'passé simple', 'ils/elles', 'chantèrent', '["chantâmes","chantèrent","chantas","chanta"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'danser', 'groupe_1', 'passé simple', 'je', 'dansai', '["dansai","dansâmes","dansâtes","dansèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'danser', 'groupe_1', 'passé simple', 'tu', 'dansas', '["dansâtes","dansèrent","dansai","dansas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'danser', 'groupe_1', 'passé simple', 'il/elle', 'dansa', '["dansai","dansas","dansa","dansèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'danser', 'groupe_1', 'passé simple', 'nous', 'dansâmes', '["dansa","dansâmes","dansai","dansas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'danser', 'groupe_1', 'passé simple', 'vous', 'dansâtes', '["dansâtes","dansas","dansa","dansâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'danser', 'groupe_1', 'passé simple', 'ils/elles', 'dansèrent', '["dansa","dansâmes","dansâtes","dansèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'donner', 'groupe_1', 'passé simple', 'je', 'donnai', '["donnèrent","donnas","donnai","donnâtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'donner', 'groupe_1', 'passé simple', 'tu', 'donnas', '["donna","donnas","donnèrent","donnai"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'donner', 'groupe_1', 'passé simple', 'il/elle', 'donna', '["donna","donnai","donnas","donnâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'donner', 'groupe_1', 'passé simple', 'nous', 'donnâmes', '["donnas","donna","donnâtes","donnâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'donner', 'groupe_1', 'passé simple', 'vous', 'donnâtes', '["donnâmes","donnèrent","donnâtes","donna"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'donner', 'groupe_1', 'passé simple', 'ils/elles', 'donnèrent', '["donnai","donnèrent","donnâmes","donnâtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'écouter', 'groupe_1', 'passé simple', 'je', 'écoutai', '["écoutai","écoutèrent","écoutas","écouta"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'écouter', 'groupe_1', 'passé simple', 'tu', 'écoutas', '["écoutai","écouta","écoutâmes","écoutas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'écouter', 'groupe_1', 'passé simple', 'il/elle', 'écouta', '["écoutâmes","écoutâtes","écouta","écoutas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'écouter', 'groupe_1', 'passé simple', 'nous', 'écoutâmes', '["écoutèrent","écoutâmes","écouta","écoutâtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'écouter', 'groupe_1', 'passé simple', 'vous', 'écoutâtes', '["écoutâtes","écoutâmes","écoutèrent","écoutai"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'écouter', 'groupe_1', 'passé simple', 'ils/elles', 'écoutèrent', '["écoutâtes","écoutai","écoutas","écoutèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'jouer', 'groupe_1', 'passé simple', 'je', 'jouai', '["joua","jouâmes","jouai","jouas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'jouer', 'groupe_1', 'passé simple', 'tu', 'jouas', '["jouâtes","jouas","joua","jouâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'jouer', 'groupe_1', 'passé simple', 'il/elle', 'joua', '["joua","jouâmes","jouâtes","jouèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'jouer', 'groupe_1', 'passé simple', 'nous', 'jouâmes', '["jouâtes","jouèrent","jouai","jouâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'jouer', 'groupe_1', 'passé simple', 'vous', 'jouâtes', '["jouai","jouas","jouâtes","jouèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'jouer', 'groupe_1', 'passé simple', 'ils/elles', 'jouèrent', '["joua","jouèrent","jouai","jouas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'manger', 'groupe_1', 'passé simple', 'je', 'mangeai', '["mangeai","mangea","mangeâmes","mangeâtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'manger', 'groupe_1', 'passé simple', 'tu', 'mangeas', '["mangeâmes","mangeâtes","mangèrent","mangeas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'manger', 'groupe_1', 'passé simple', 'il/elle', 'mangea', '["mangèrent","mangeai","mangea","mangeâtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'manger', 'groupe_1', 'passé simple', 'nous', 'mangeâmes', '["mangeas","mangeâmes","mangèrent","mangeai"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'manger', 'groupe_1', 'passé simple', 'vous', 'mangeâtes', '["mangeâtes","mangeai","mangeas","mangea"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'manger', 'groupe_1', 'passé simple', 'ils/elles', 'mangèrent', '["mangeas","mangea","mangeâmes","mangèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'marcher', 'groupe_1', 'passé simple', 'je', 'marchai', '["marchâtes","marchèrent","marchai","marchâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'marcher', 'groupe_1', 'passé simple', 'tu', 'marchas', '["marchai","marchas","marchâtes","marchèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'marcher', 'groupe_1', 'passé simple', 'il/elle', 'marcha', '["marcha","marchèrent","marchai","marchas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'marcher', 'groupe_1', 'passé simple', 'nous', 'marchâmes', '["marchai","marchas","marcha","marchâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'marcher', 'groupe_1', 'passé simple', 'vous', 'marchâtes', '["marcha","marchâmes","marchâtes","marchas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'marcher', 'groupe_1', 'passé simple', 'ils/elles', 'marchèrent', '["marchâtes","marchèrent","marcha","marchâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'parler', 'groupe_1', 'passé simple', 'je', 'parlai', '["parlai","parlâtes","parlèrent","parlas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'parler', 'groupe_1', 'passé simple', 'tu', 'parlas', '["parlèrent","parlai","parla","parlas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'parler', 'groupe_1', 'passé simple', 'il/elle', 'parla', '["parlas","parlâmes","parla","parlai"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'parler', 'groupe_1', 'passé simple', 'nous', 'parlâmes', '["parlâtes","parlâmes","parlas","parla"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'parler', 'groupe_1', 'passé simple', 'vous', 'parlâtes', '["parlâtes","parla","parlâmes","parlèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'parler', 'groupe_1', 'passé simple', 'ils/elles', 'parlèrent', '["parlâmes","parlâtes","parlai","parlèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'regarder', 'groupe_1', 'passé simple', 'je', 'regardai', '["regardas","regarda","regardai","regardèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'regarder', 'groupe_1', 'passé simple', 'tu', 'regardas', '["regardâmes","regardas","regardai","regarda"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'regarder', 'groupe_1', 'passé simple', 'il/elle', 'regarda', '["regarda","regardas","regardâmes","regardâtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'regarder', 'groupe_1', 'passé simple', 'nous', 'regardâmes', '["regarda","regardâtes","regardèrent","regardâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'regarder', 'groupe_1', 'passé simple', 'vous', 'regardâtes', '["regardèrent","regardai","regardâtes","regardâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'regarder', 'groupe_1', 'passé simple', 'ils/elles', 'regardèrent', '["regardas","regardèrent","regardâtes","regardai"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'travailler', 'groupe_1', 'passé simple', 'je', 'travaillai', '["travaillai","travaillas","travailla","travaillâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'travailler', 'groupe_1', 'passé simple', 'tu', 'travaillas', '["travailla","travaillâmes","travaillâtes","travaillas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'travailler', 'groupe_1', 'passé simple', 'il/elle', 'travailla', '["travaillâtes","travaillèrent","travailla","travaillâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'travailler', 'groupe_1', 'passé simple', 'nous', 'travaillâmes', '["travaillai","travaillâmes","travaillâtes","travaillèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'travailler', 'groupe_1', 'passé simple', 'vous', 'travaillâtes', '["travaillâtes","travaillèrent","travaillai","travaillas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'travailler', 'groupe_1', 'passé simple', 'ils/elles', 'travaillèrent', '["travaillai","travaillas","travailla","travaillèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'trouver', 'groupe_1', 'passé simple', 'je', 'trouvai', '["trouvâmes","trouvâtes","trouvai","trouva"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'trouver', 'groupe_1', 'passé simple', 'tu', 'trouvas', '["trouvèrent","trouvas","trouvâmes","trouvâtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'trouver', 'groupe_1', 'passé simple', 'il/elle', 'trouva', '["trouva","trouvâtes","trouvèrent","trouvai"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'trouver', 'groupe_1', 'passé simple', 'nous', 'trouvâmes', '["trouvèrent","trouvai","trouvas","trouvâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'trouver', 'groupe_1', 'passé simple', 'vous', 'trouvâtes', '["trouvas","trouva","trouvâtes","trouvai"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'trouver', 'groupe_1', 'passé simple', 'ils/elles', 'trouvèrent', '["trouvâmes","trouvèrent","trouvas","trouva"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'choisir', 'groupe_2', 'passé simple', 'je', 'choisis', '["choisis","choisit","choisîmes","choisîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'choisir', 'groupe_2', 'passé simple', 'tu', 'choisis', '["choisîmes","choisîtes","choisirent","choisis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'choisir', 'groupe_2', 'passé simple', 'il/elle', 'choisit', '["choisirent","choisis","choisit","choisîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'choisir', 'groupe_2', 'passé simple', 'nous', 'choisîmes', '["choisit","choisîmes","choisirent","choisis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'choisir', 'groupe_2', 'passé simple', 'vous', 'choisîtes', '["choisîtes","choisis","choisit","choisîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'choisir', 'groupe_2', 'passé simple', 'ils/elles', 'choisirent', '["choisit","choisîmes","choisîtes","choisirent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'finir', 'groupe_2', 'passé simple', 'je', 'finis', '["finirent","finit","finis","finîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'finir', 'groupe_2', 'passé simple', 'tu', 'finis', '["finîmes","finis","finirent","finit"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'finir', 'groupe_2', 'passé simple', 'il/elle', 'finit', '["finit","finis","finîmes","finîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'finir', 'groupe_2', 'passé simple', 'nous', 'finîmes', '["finit","finîtes","finirent","finîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'finir', 'groupe_2', 'passé simple', 'vous', 'finîtes', '["finirent","finis","finîtes","finîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'finir', 'groupe_2', 'passé simple', 'ils/elles', 'finirent', '["finit","finirent","finîtes","finis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grandir', 'groupe_2', 'passé simple', 'je', 'grandis', '["grandis","grandit","grandîmes","grandîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grandir', 'groupe_2', 'passé simple', 'tu', 'grandis', '["grandîmes","grandîtes","grandirent","grandis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grandir', 'groupe_2', 'passé simple', 'il/elle', 'grandit', '["grandirent","grandis","grandit","grandîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grandir', 'groupe_2', 'passé simple', 'nous', 'grandîmes', '["grandit","grandîmes","grandirent","grandis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grandir', 'groupe_2', 'passé simple', 'vous', 'grandîtes', '["grandîtes","grandis","grandit","grandîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grandir', 'groupe_2', 'passé simple', 'ils/elles', 'grandirent', '["grandit","grandîmes","grandîtes","grandirent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grossir', 'groupe_2', 'passé simple', 'je', 'grossis', '["grossirent","grossit","grossis","grossîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grossir', 'groupe_2', 'passé simple', 'tu', 'grossis', '["grossîmes","grossis","grossirent","grossit"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grossir', 'groupe_2', 'passé simple', 'il/elle', 'grossit', '["grossit","grossis","grossîmes","grossîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grossir', 'groupe_2', 'passé simple', 'nous', 'grossîmes', '["grossit","grossîtes","grossirent","grossîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grossir', 'groupe_2', 'passé simple', 'vous', 'grossîtes', '["grossirent","grossis","grossîtes","grossîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'grossir', 'groupe_2', 'passé simple', 'ils/elles', 'grossirent', '["grossit","grossirent","grossîtes","grossis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'maigrir', 'groupe_2', 'passé simple', 'je', 'maigris', '["maigris","maigrit","maigrîmes","maigrîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'maigrir', 'groupe_2', 'passé simple', 'tu', 'maigris', '["maigrîmes","maigrîtes","maigrirent","maigris"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'maigrir', 'groupe_2', 'passé simple', 'il/elle', 'maigrit', '["maigrirent","maigris","maigrit","maigrîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'maigrir', 'groupe_2', 'passé simple', 'nous', 'maigrîmes', '["maigrit","maigrîmes","maigrirent","maigris"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'maigrir', 'groupe_2', 'passé simple', 'vous', 'maigrîtes', '["maigrîtes","maigris","maigrit","maigrîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'maigrir', 'groupe_2', 'passé simple', 'ils/elles', 'maigrirent', '["maigrit","maigrîmes","maigrîtes","maigrirent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'obéir', 'groupe_2', 'passé simple', 'je', 'obéis', '["obéirent","obéit","obéis","obéîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'obéir', 'groupe_2', 'passé simple', 'tu', 'obéis', '["obéîmes","obéis","obéirent","obéit"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'obéir', 'groupe_2', 'passé simple', 'il/elle', 'obéit', '["obéit","obéis","obéîmes","obéîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'obéir', 'groupe_2', 'passé simple', 'nous', 'obéîmes', '["obéit","obéîtes","obéirent","obéîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'obéir', 'groupe_2', 'passé simple', 'vous', 'obéîtes', '["obéirent","obéis","obéîtes","obéîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'obéir', 'groupe_2', 'passé simple', 'ils/elles', 'obéirent', '["obéit","obéirent","obéîtes","obéis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'punir', 'groupe_2', 'passé simple', 'je', 'punis', '["punis","punit","punîmes","punîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'punir', 'groupe_2', 'passé simple', 'tu', 'punis', '["punîmes","punîtes","punirent","punis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'punir', 'groupe_2', 'passé simple', 'il/elle', 'punit', '["punirent","punis","punit","punîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'punir', 'groupe_2', 'passé simple', 'nous', 'punîmes', '["punit","punîmes","punirent","punis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'punir', 'groupe_2', 'passé simple', 'vous', 'punîtes', '["punîtes","punis","punit","punîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'punir', 'groupe_2', 'passé simple', 'ils/elles', 'punirent', '["punit","punîmes","punîtes","punirent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'réussir', 'groupe_2', 'passé simple', 'je', 'réussis', '["réussirent","réussit","réussis","réussîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'réussir', 'groupe_2', 'passé simple', 'tu', 'réussis', '["réussîmes","réussis","réussirent","réussit"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'réussir', 'groupe_2', 'passé simple', 'il/elle', 'réussit', '["réussit","réussis","réussîmes","réussîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'réussir', 'groupe_2', 'passé simple', 'nous', 'réussîmes', '["réussit","réussîtes","réussirent","réussîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'réussir', 'groupe_2', 'passé simple', 'vous', 'réussîtes', '["réussirent","réussis","réussîtes","réussîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'réussir', 'groupe_2', 'passé simple', 'ils/elles', 'réussirent', '["réussit","réussirent","réussîtes","réussis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'remplir', 'groupe_2', 'passé simple', 'je', 'remplis', '["remplis","remplit","remplîmes","remplîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'remplir', 'groupe_2', 'passé simple', 'tu', 'remplis', '["remplîmes","remplîtes","remplirent","remplis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'remplir', 'groupe_2', 'passé simple', 'il/elle', 'remplit', '["remplirent","remplis","remplit","remplîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'remplir', 'groupe_2', 'passé simple', 'nous', 'remplîmes', '["remplit","remplîmes","remplirent","remplis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'remplir', 'groupe_2', 'passé simple', 'vous', 'remplîtes', '["remplîtes","remplis","remplit","remplîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'remplir', 'groupe_2', 'passé simple', 'ils/elles', 'remplirent', '["remplit","remplîmes","remplîtes","remplirent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rougir', 'groupe_2', 'passé simple', 'je', 'rougis', '["rougirent","rougit","rougis","rougîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rougir', 'groupe_2', 'passé simple', 'tu', 'rougis', '["rougîmes","rougis","rougirent","rougit"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rougir', 'groupe_2', 'passé simple', 'il/elle', 'rougit', '["rougit","rougis","rougîmes","rougîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rougir', 'groupe_2', 'passé simple', 'nous', 'rougîmes', '["rougit","rougîtes","rougirent","rougîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rougir', 'groupe_2', 'passé simple', 'vous', 'rougîtes', '["rougirent","rougis","rougîtes","rougîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rougir', 'groupe_2', 'passé simple', 'ils/elles', 'rougirent', '["rougit","rougirent","rougîtes","rougis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'attendre', 'groupe_3', 'passé simple', 'je', 'attendis', '["attendis","attendit","attendîmes","attendîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'attendre', 'groupe_3', 'passé simple', 'tu', 'attendis', '["attendîmes","attendîtes","attendirent","attendis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'attendre', 'groupe_3', 'passé simple', 'il/elle', 'attendit', '["attendirent","attendis","attendit","attendîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'attendre', 'groupe_3', 'passé simple', 'nous', 'attendîmes', '["attendit","attendîmes","attendirent","attendis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'attendre', 'groupe_3', 'passé simple', 'vous', 'attendîtes', '["attendîtes","attendis","attendit","attendîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'attendre', 'groupe_3', 'passé simple', 'ils/elles', 'attendirent', '["attendit","attendîmes","attendîtes","attendirent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'entendre', 'groupe_3', 'passé simple', 'je', 'entendis', '["entendirent","entendit","entendis","entendîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'entendre', 'groupe_3', 'passé simple', 'tu', 'entendis', '["entendîmes","entendis","entendirent","entendit"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'entendre', 'groupe_3', 'passé simple', 'il/elle', 'entendit', '["entendit","entendis","entendîmes","entendîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'entendre', 'groupe_3', 'passé simple', 'nous', 'entendîmes', '["entendit","entendîtes","entendirent","entendîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'entendre', 'groupe_3', 'passé simple', 'vous', 'entendîtes', '["entendirent","entendis","entendîtes","entendîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'entendre', 'groupe_3', 'passé simple', 'ils/elles', 'entendirent', '["entendit","entendirent","entendîtes","entendis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'perdre', 'groupe_3', 'passé simple', 'je', 'perdis', '["perdis","perdit","perdîmes","perdîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'perdre', 'groupe_3', 'passé simple', 'tu', 'perdis', '["perdîmes","perdîtes","perdirent","perdis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'perdre', 'groupe_3', 'passé simple', 'il/elle', 'perdit', '["perdirent","perdis","perdit","perdîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'perdre', 'groupe_3', 'passé simple', 'nous', 'perdîmes', '["perdit","perdîmes","perdirent","perdis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'perdre', 'groupe_3', 'passé simple', 'vous', 'perdîtes', '["perdîtes","perdis","perdit","perdîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'perdre', 'groupe_3', 'passé simple', 'ils/elles', 'perdirent', '["perdit","perdîmes","perdîtes","perdirent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rendre', 'groupe_3', 'passé simple', 'je', 'rendis', '["rendirent","rendit","rendis","rendîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rendre', 'groupe_3', 'passé simple', 'tu', 'rendis', '["rendîmes","rendis","rendirent","rendit"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rendre', 'groupe_3', 'passé simple', 'il/elle', 'rendit', '["rendit","rendis","rendîmes","rendîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rendre', 'groupe_3', 'passé simple', 'nous', 'rendîmes', '["rendit","rendîtes","rendirent","rendîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rendre', 'groupe_3', 'passé simple', 'vous', 'rendîtes', '["rendirent","rendis","rendîtes","rendîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'rendre', 'groupe_3', 'passé simple', 'ils/elles', 'rendirent', '["rendit","rendirent","rendîtes","rendis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'répondre', 'groupe_3', 'passé simple', 'je', 'répondis', '["répondis","répondit","répondîmes","répondîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'répondre', 'groupe_3', 'passé simple', 'tu', 'répondis', '["répondîmes","répondîtes","répondirent","répondis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'répondre', 'groupe_3', 'passé simple', 'il/elle', 'répondit', '["répondirent","répondis","répondit","répondîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'répondre', 'groupe_3', 'passé simple', 'nous', 'répondîmes', '["répondit","répondîmes","répondirent","répondis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'répondre', 'groupe_3', 'passé simple', 'vous', 'répondîtes', '["répondîtes","répondis","répondit","répondîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'répondre', 'groupe_3', 'passé simple', 'ils/elles', 'répondirent', '["répondit","répondîmes","répondîtes","répondirent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vendre', 'groupe_3', 'passé simple', 'je', 'vendis', '["vendirent","vendit","vendis","vendîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vendre', 'groupe_3', 'passé simple', 'tu', 'vendis', '["vendîmes","vendis","vendirent","vendit"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vendre', 'groupe_3', 'passé simple', 'il/elle', 'vendit', '["vendit","vendis","vendîmes","vendîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vendre', 'groupe_3', 'passé simple', 'nous', 'vendîmes', '["vendit","vendîtes","vendirent","vendîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vendre', 'groupe_3', 'passé simple', 'vous', 'vendîtes', '["vendirent","vendis","vendîtes","vendîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vendre', 'groupe_3', 'passé simple', 'ils/elles', 'vendirent', '["vendit","vendirent","vendîtes","vendis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'être', 'irregulier', 'passé simple', 'je', 'fus', '["fus","fut","fûmes","fûtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'être', 'irregulier', 'passé simple', 'tu', 'fus', '["fûmes","fûtes","furent","fus"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'être', 'irregulier', 'passé simple', 'il/elle', 'fut', '["furent","fus","fut","fûtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'être', 'irregulier', 'passé simple', 'nous', 'fûmes', '["fut","fûmes","furent","fus"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'être', 'irregulier', 'passé simple', 'vous', 'fûtes', '["fûtes","fus","fut","fûmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'être', 'irregulier', 'passé simple', 'ils/elles', 'furent', '["fut","fûmes","fûtes","furent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'avoir', 'irregulier', 'passé simple', 'je', 'eus', '["eurent","eut","eus","eûtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'avoir', 'irregulier', 'passé simple', 'tu', 'eus', '["eûmes","eus","eurent","eut"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'avoir', 'irregulier', 'passé simple', 'il/elle', 'eut', '["eut","eus","eûmes","eûtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'avoir', 'irregulier', 'passé simple', 'nous', 'eûmes', '["eut","eûtes","eurent","eûmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'avoir', 'irregulier', 'passé simple', 'vous', 'eûtes', '["eurent","eus","eûtes","eûmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'avoir', 'irregulier', 'passé simple', 'ils/elles', 'eurent', '["eut","eurent","eûtes","eus"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'aller', 'irregulier', 'passé simple', 'je', 'allai', '["allai","allas","alla","allâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'aller', 'irregulier', 'passé simple', 'tu', 'allas', '["alla","allâmes","allâtes","allas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'aller', 'irregulier', 'passé simple', 'il/elle', 'alla', '["allâtes","allèrent","alla","allâmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'aller', 'irregulier', 'passé simple', 'nous', 'allâmes', '["allai","allâmes","allâtes","allèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'aller', 'irregulier', 'passé simple', 'vous', 'allâtes', '["allâtes","allèrent","allai","allas"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'aller', 'irregulier', 'passé simple', 'ils/elles', 'allèrent', '["allai","allas","alla","allèrent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'faire', 'irregulier', 'passé simple', 'je', 'fis', '["firent","fit","fis","fîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'faire', 'irregulier', 'passé simple', 'tu', 'fis', '["fîmes","fis","firent","fit"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'faire', 'irregulier', 'passé simple', 'il/elle', 'fit', '["fit","fis","fîmes","fîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'faire', 'irregulier', 'passé simple', 'nous', 'fîmes', '["fit","fîtes","firent","fîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'faire', 'irregulier', 'passé simple', 'vous', 'fîtes', '["firent","fis","fîtes","fîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'faire', 'irregulier', 'passé simple', 'ils/elles', 'firent', '["fit","firent","fîtes","fis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'dire', 'irregulier', 'passé simple', 'je', 'dis', '["dis","dit","dîmes","dîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'dire', 'irregulier', 'passé simple', 'tu', 'dis', '["dîmes","dîtes","dirent","dis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'dire', 'irregulier', 'passé simple', 'il/elle', 'dit', '["dirent","dis","dit","dîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'dire', 'irregulier', 'passé simple', 'nous', 'dîmes', '["dit","dîmes","dirent","dis"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'dire', 'irregulier', 'passé simple', 'vous', 'dîtes', '["dîtes","dis","dit","dîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'dire', 'irregulier', 'passé simple', 'ils/elles', 'dirent', '["dit","dîmes","dîtes","dirent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'venir', 'irregulier', 'passé simple', 'je', 'vins', '["vinrent","vint","vins","vîntes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'venir', 'irregulier', 'passé simple', 'tu', 'vins', '["vînmes","vins","vinrent","vint"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'venir', 'irregulier', 'passé simple', 'il/elle', 'vint', '["vint","vins","vînmes","vîntes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'venir', 'irregulier', 'passé simple', 'nous', 'vînmes', '["vint","vîntes","vinrent","vînmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'venir', 'irregulier', 'passé simple', 'vous', 'vîntes', '["vinrent","vins","vîntes","vînmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'venir', 'irregulier', 'passé simple', 'ils/elles', 'vinrent', '["vint","vinrent","vîntes","vins"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'prendre', 'irregulier', 'passé simple', 'je', 'pris', '["pris","prit","prîmes","prîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'prendre', 'irregulier', 'passé simple', 'tu', 'pris', '["prîmes","prîtes","prirent","pris"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'prendre', 'irregulier', 'passé simple', 'il/elle', 'prit', '["prirent","pris","prit","prîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'prendre', 'irregulier', 'passé simple', 'nous', 'prîmes', '["prit","prîmes","prirent","pris"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'prendre', 'irregulier', 'passé simple', 'vous', 'prîtes', '["prîtes","pris","prit","prîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'prendre', 'irregulier', 'passé simple', 'ils/elles', 'prirent', '["prit","prîmes","prîtes","prirent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'pouvoir', 'irregulier', 'passé simple', 'je', 'pus', '["purent","put","pus","pûtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'pouvoir', 'irregulier', 'passé simple', 'tu', 'pus', '["pûmes","pus","purent","put"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'pouvoir', 'irregulier', 'passé simple', 'il/elle', 'put', '["put","pus","pûmes","pûtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'pouvoir', 'irregulier', 'passé simple', 'nous', 'pûmes', '["put","pûtes","purent","pûmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'pouvoir', 'irregulier', 'passé simple', 'vous', 'pûtes', '["purent","pus","pûtes","pûmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'pouvoir', 'irregulier', 'passé simple', 'ils/elles', 'purent', '["put","purent","pûtes","pus"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vouloir', 'irregulier', 'passé simple', 'je', 'voulus', '["voulus","voulut","voulûmes","voulûtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vouloir', 'irregulier', 'passé simple', 'tu', 'voulus', '["voulûmes","voulûtes","voulurent","voulus"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vouloir', 'irregulier', 'passé simple', 'il/elle', 'voulut', '["voulurent","voulus","voulut","voulûtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vouloir', 'irregulier', 'passé simple', 'nous', 'voulûmes', '["voulut","voulûmes","voulurent","voulus"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vouloir', 'irregulier', 'passé simple', 'vous', 'voulûtes', '["voulûtes","voulus","voulut","voulûmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'vouloir', 'irregulier', 'passé simple', 'ils/elles', 'voulurent', '["voulut","voulûmes","voulûtes","voulurent"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'voir', 'irregulier', 'passé simple', 'je', 'vis', '["virent","vit","vis","vîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'voir', 'irregulier', 'passé simple', 'tu', 'vis', '["vîmes","vis","virent","vit"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'voir', 'irregulier', 'passé simple', 'il/elle', 'vit', '["vit","vis","vîmes","vîtes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'voir', 'irregulier', 'passé simple', 'nous', 'vîmes', '["vit","vîtes","virent","vîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'voir', 'irregulier', 'passé simple', 'vous', 'vîtes', '["virent","vis","vîtes","vîmes"]'::jsonb, '["CM1"]'::jsonb, 4),
  ('fr-FR', 'voir', 'irregulier', 'passé simple', 'ils/elles', 'virent', '["vit","virent","vîtes","vis"]'::jsonb, '["CM1"]'::jsonb, 4)
) as v(language, verb, verb_group, tense, pronoun, correct_answer, options, grade_levels, difficulty_level)
where not exists (
  select 1
  from public.conjugation_questions q
  where q.language = v.language
    and q.verb = v.verb
    and q.verb_group = v.verb_group
    and q.tense = v.tense
    and q.pronoun = v.pronoun
);
